import type { PublicProfile } from '@/lib/types';
import alex from '@/assets/demo/alex.png'; import samira from '@/assets/demo/samira.png'; import noa from '@/assets/demo/noa.png'; import camille from '@/assets/demo/camille.png'; import jules from '@/assets/demo/jules.png'; import eden from '@/assets/demo/eden.png';
const b={email:null,phone:null,civilite:'Iel' as const,pronouns:'iel',bio:null,needs:[],intervention_zone:null,budget_indicatif:null,linkedin_url:null,external_reviews_url:null,charte_accepted:true,charte_accepted_at:null,verification_status:'verified' as const,verified_at:null,profile_status:'active' as const,is_admin:false,is_community_member:true,is_ally:false,created_at:'2026-09-01T10:00:00Z',updated_at:'2026-09-01T10:00:00Z'};
export const SCREENSHOT_DEMO_PROFILES:PublicProfile[]=[
 {...b,id:'demo-alex',display_name:'Inès D.',account_type:'particulier',city:'Paris',bio:'Je donne un coup de main pour les petits travaux et le montage de meubles.',skills:['Montage & bricolage'],indicative_rates:'25 € / heure',photo_url:alex}, {...b,id:'demo-samira',display_name:'Malik L.',account_type:'particulier',city:'Lyon',bio:'Disponible pour l’aide à domicile avec bienveillance.',skills:['Ménage & aide'],indicative_rates:'20 € / heure',photo_url:samira}, {...b,id:'demo-noa',display_name:'Noa R.',account_type:'particulier',city:'Bordeaux',bio:'Passionnée par les animaux et attentive à leurs habitudes.',skills:['Garde d’animaux'],indicative_rates:'18 € / heure',photo_url:noa}, {...b,id:'demo-camille',display_name:'Thomas P.',account_type:'pro',city:'Marseille',bio:'J’aide à prendre en main l’informatique du quotidien.',skills:['Informatique'],indicative_rates:'35 € / heure',photo_url:camille}, {...b,id:'demo-jules',display_name:'Jade M.',account_type:'particulier',city:'Nantes',bio:'Pour entretenir et faire vivre les petits jardins.',skills:['Jardinage'],indicative_rates:'22 € / heure',photo_url:jules}, {...b,id:'demo-eden',display_name:'Hugo S.',account_type:'particulier',city:'Lille',bio:'Disponible pour les trajets et les petits déménagements.',skills:['Transport & déménagement'],indicative_rates:'30 € / heure',photo_url:eden}
];

export const SCREENSHOT_DEMO_MISSIONS = [
 {id:'demo-mission-1',title:'Aide pour monter une bibliothèque',description:'Je viens d’emménager à Lille et cherche une personne soigneuse pour monter une bibliothèque et fixer deux étagères. Outillage bienvenu.',budget:'50 €',created_at:'2026-09-28T15:30:00Z',created_by:'demo-hugo',profiles:{display_name:'Léa B.',photo_url:noa}},
 {id:'demo-mission-2',title:'Garde de chat ce week-end',description:'Je cherche une visite par jour pour nourrir et tenir compagnie à mon chat, du samedi au lundi. Quartier Saint-Michel.',budget:'15 € / visite',created_at:'2026-09-28T12:15:00Z',created_by:'demo-noa',profiles:{display_name:'Camille R.',photo_url:jules}},
 {id:'demo-mission-3',title:'Besoin d’aide pour un déménagement',description:'Quelques cartons et un petit canapé à déplacer samedi après-midi. Le trajet est court, entre Wazemmes et le centre de Lille.',budget:'60 €',created_at:'2026-09-27T17:00:00Z',created_by:'demo-alex',profiles:{display_name:'Inès D.',photo_url:alex}},
 {id:'demo-mission-4',title:'Ordinateur portable à configurer',description:'J’aimerais être aidé·e à installer mon nouvel ordinateur, transférer mes documents et comprendre les réglages essentiels.',budget:'35 €',created_at:'2026-09-27T10:30:00Z',created_by:'demo-camille',profiles:{display_name:'Thomas P.',photo_url:camille}},
] as const;
